package leetcode_389;
/**
 *  leetcode 389 Find the difference
 *
 Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */
public class FindTheDifference {
    private String[] args;

    public static char findTheDifference1(String s, String t) {
        int[] chars = new int[26];
        for(int i = 0; i < s.length();i++){
            chars[s.charAt(i) - 'a']++;
        }
        for(int i = 0; i < t.length();i++){
            chars[t.charAt(i) - 'a']--;
        }
        char ans = 'a';
        for(int i = 0; i < 26; i++){
            if(chars[i] != 0) ans = (char)('a' + i);
        }
        return ans;
    }
    public static char findTheDifference2(String s, String t){
        int res = 0;
        for( char c : s.toCharArray()) res = res ^ c;
        for( char c : t.toCharArray()) res = res ^ c;
        return (char)(res);
    }
    public static void main(String[] args){
        System.out.print(findTheDifference1("abcd","abcde"));
        System.out.print(findTheDifference2("abcd","abcde"));
    }
}
